apps/info/urls.py
from django.urls import path

from . import views

app_name = "info"

urlpatterns = [
    path("", views.index, name="index"),
    path("terms-and-conditions/", views.TermsAndConditionsView.as_view(), name="terms_and_conditions"),
    path("privacy-policy/", views.PrivacyPolicyView.as_view(), name="privacy_policy"),
]

apps/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("public-profile/<int:user_id>/", views.PublicProfileView.as_view(), name="public_profile"),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("", include("apps.info.urls")),
    path("users/", include("apps.users.urls", namespace="users")),
    path("dashboard/", include("apps.dashboard.urls", namespace="dashboard")),
    path("rankings/", include("apps.rankings.urls", namespace="rankings")),
    path("geo/", include("apps.geo.urls", namespace="geo")),
    path("tienda/", include("apps.store.urls", namespace="store")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class Player(AbstractUser):
    # Reputation score field
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    reputation_score = models.IntegerField(default=0, verbose_name='Puntuación de Reputación')

apps/users/forms.py
# apps/users/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
    AuthenticationForm,
)
from .models import Player


class PlayerCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Player
        fields = ("username", "email", "reputation_score", "avatar")


class PlayerChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = Player
        fields = ("username", "email", "reputation_score", "avatar")


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                "class": "input",
                "placeholder": "Tu apodo en la cancha, cómo te conocerán todos",
            }
        ),
    )

    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={
                "class": "input",
                "placeholder": "Tu correo para no perderte nada",
            }
        ),
    )

    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "class": "input",
                "placeholder": "Elige algo seguro para proteger tu cuenta",
            }
        ),
    )

    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                "class": "input",
                "placeholder": "Repetir contraseña",
            }
        ),
    )

    class Meta:
        model = Player
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "input",
                "placeholder": "Nombre de Jugador",
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "input",
                "placeholder": "Contraseña",
            }
        )
    )

apps/users/views.py
from datetime import timedelta
from django.utils import timezone
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from apps.rankings.models import PlayerRanking
from apps.teams.models import Team
from apps.competitions.models import Match
from apps.users.forms import CustomLoginForm, SignUpForm
from django.contrib.auth import logout
from django.views.generic import TemplateView
from django.db.models import Q
from django.db.models.functions import TruncDate
from apps.users.models import Player


# Create your views here.
class CustomLoginView(LoginView):
    template_name = "login.html"
    authentication_form = CustomLoginForm

    def get_success_url(self):
        return reverse_lazy("dashboard:dashboard")


class SignUpView(FormView):
    template_name = "signup.html"
    form_class = SignUpForm
    success_url = reverse_lazy("dashboard:dashboard")

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("dashboard:dashboard")
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.save()
        CustomLoginView(self.request, user)
        return super().form_valid(form)


class CustomLogoutView(LogoutView):
    def post(self, request, *args, **kwargs):
        logout(request)
        redirect_url = reverse_lazy("users:login")  # o cualquier otra ruta
        response = JsonResponse({}, status=200)
        response["HX-Redirect"] = redirect_url
        return response


class PublicProfileView(TemplateView):
    template_name = "public_profile.html"
    success_url = reverse_lazy("dashboard:dashboard")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_id = self.kwargs.get("user_id")
        user = self.get_user(user_id)
        context["user"] = user
        context["total_games"] = _get_player_number_of_games(user)
        context["current_elo"] = _get_player_current_elo(user)
        context["highest_elo"] = _get_highest_elo(user)
        context["reputation"] = user.reputation_score
        context["current_teams"] = _get_player_current_teams(user)
        return context

    def get_user(self, user_id):
        try:
            return Player.objects.get(id=user_id)
        except Player.DoesNotExist:
            return None


def _get_player_number_of_games(player):
    teams = Team.objects.filter(members__player=player)
    return (
        Match.objects.filter(Q(winner_team__in=teams) | Q(loser_team__in=teams))
        .distinct()
        .count()
    )


def _get_player_current_elo(player):
    current_elo = PlayerRanking.objects.filter(player=player).first()
    return current_elo.elo if current_elo else None


def _get_highest_elo(player):
    return (
        PlayerRanking.objects.filter(player=player)
        .order_by("-elo")
        .values_list("elo", flat=True)
        .first()
    )

def _get_player_current_teams(player):
    return Team.objects.filter(members__player=player, is_active=True).distinct()

apps/users/templates/achivement_card.html
{% load static %}
<ul class="list bg-base-100 rounded-box shadow-md">
  {% for achivement in achivements %}
    <li class="list-row">
      <div class="avatar">
        <div class="mask mask-squircle w-18">
          {% if achivement.logo %}
            <img src="{{ achivement.logo.url }}" alt="Achivement" width="150" />
          {% else %}
            <img src="{% static 'images/default_achivement.webp' %}" alt="Achivement por defecto" width="150" />
          {% endif %}
        </div>
      </div>
      <div>
        <div class="text-2xl">{{ achivement.name }}</div>
        <div class="text-xl uppercase font-semibold opacity-60">{{ achivement.description }}</div>
      </div>
    </li>
  {% endfor %}
</ul>

apps/users/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="hero bg-base-200 min-h-screen">
    <div class="hero-content flex-col lg:flex-row-reverse">
      <div class="text-center lg:text-left">
        <h1 class="text-5xl font-bold">VUELVE A LA CANCHA</h1>
        <p class="pt-6">Tus rivales te están esperando.</p>
        <div class="divider"></div>
        <p>
          ¿Nuevo en la cancha?{% url 'users:signup' as url %}
          {% with url=url label='Regístrate aquí' extra_classes='link link-secondary link-hover' %}
            {% include 'components/button.html' %}
          {% endwith %}
        </p>
      </div>
      <div class="card bg-base-100 w-full max-w-sm shrink-0 shadow-2xl">
        <div class="card-body">
          <form method="post" class="space-y-4">
            <fieldset class="fieldset">
              {% csrf_token %}
              <label class="label">Nombre de Jugador</label>
              {{ form.username }}
              {% if form.username.errors %}
                <p class="text-red-500 text-xs">{{ form.username.errors.0 }}</p>
              {% endif %}
              <label class="label">Contraseña</label>
              {{ form.password }}
              {% if form.password.errors %}
                <p class="text-red-500 text-xs">{{ form.password.errors.0 }}</p>
              {% endif %}
              <div>
                <a class="link link-hover">¿Olvidaste tu contraseña?</a>
              </div>
              <button type="submit" class="btn btn-primary">Entrar</button>
              <a href="{% url 'info:index' %}" class="btn btn-neutral">Cancelar</a>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

apps/users/templates/public_profile.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
  {% include 'components/navbar.html' %}
{% endblock %}

{% block content %}
  <section class="mt-4">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <div class="avatar justify-self-center">
        <div class="mask mask-squircle w-80">
          {% if user.avatar %}
            <img src="{{ user.avatar.url }}" alt="Logo del jugador" />
          {% else %}
            <img src="{% static 'images/default_avatar.webp' %}" alt="Logo por defecto" width="150" />
          {% endif %}
        </div>
      </div>
      <div class="justify-self-center mt-2">
        <div class="text-center text-6xl">{{ user.username }}</div>
        <div class="mt-4">
          <div class="stats stats-vertical lg:stats-horizontal shadow">
            <div class="stat place-items-center">
              <div class="stat-title text-2xl">Partidos Jugados</div>
              <div class="stat-value text-6xl">{{ total_games }}</div>
              <div class="stat-desc text-xl">Jan 1st - Feb 1st</div>
            </div>

            <div class="stat place-items-center">
              <div class="stat-title text-2xl">ELO</div>
              <div class="stat-value text-6xl">{{ current_elo }}</div>
              <div class="stat-desc text-xl">
                <div class="badge badge-primary">Oro</div>{{ highest_elo }}
              </div>
            </div>

            <div class="stat place-items-center">
              <div class="stat-title text-2xl">Reputación</div>
              <div class="stat-value text-6xl">{{ reputation }}%</div>
              <div class="stat-desc text-xl">Comportamiento ejemplar</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="my-4">
    <!-- name of each tab group should be unique -->
    <div class="tabs tabs-box">
      <input type="radio" name="my_tabs_6" class="tab" aria-label="Equipos" checked="checked" />
      <div class="tab-content bg-base-200 border-base-300 p-6">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <h2>Equipos Actuales</h2>
            {% include 'components/team_card.html' with teams=current_teams %}
          </div>
          <div>
            <h2>Historial de equipos</h2>
            {% include 'components/team_card.html' with teams=historical_teams %}
          </div>
        </div>
      </div>

      <input type="radio" name="my_tabs_6" class="tab" aria-label="Vitrina" />
      <div class="tab-content bg-base-200 border-base-300 p-6">No hay datos todavía</div>

      <input type="radio" name="my_tabs_6" class="tab" aria-label="Ligas y Torneos" />
      <div class="tab-content bg-base-200 border-base-300 p-6">No hay datos todavía</div>
    </div>
  </section>
{% endblock %}

apps/users/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="hero bg-base-200 min-h-screen">
    <div class="hero-content flex-col lg:flex-row-reverse">
      <div class="text-center lg:text-left">
        <h1 class="text-5xl font-bold">FORJA TU LEYENDA</h1>
        <p class="pt-6">Crea tu perfil y empieza a competir. El asfalto te espera.</p>
        <div class="divider"></div>
        <p>
          ¿Ya tienes cuenta?{% url 'users:login' as url %}
          {% with url=url label='Inicia sesión' extra_classes='link link-secondary link-hover' %}
            {% include 'components/button.html' %}
          {% endwith %}
        </p>
      </div>
      <div class="card bg-base-100 w-full max-w-sm shrink-0 shadow-2xl">
        <div class="card-body">
          <form method="post" class="space-y-4">
            <fieldset class="fieldset">
              {% csrf_token %}
              <label class="label">Nombre de Jugador</label>
              {{ form.username }}
              {% if form.username.errors %}
                <p class="text-red-500 text-xs">{{ form.username.errors.0 }}</p>
              {% endif %}
              <label class="label">Email</label>
              {{ form.email }}
              {% if form.email.errors %}
                <p class="text-red-500 text-xs">{{ form.email.errors.0 }}</p>
              {% endif %}
              <label class="label">Contraseña</label>
              {{ form.password1 }}
              {% if form.password1.errors %}
                <p class="text-red-500 text-xs">{{ form.password1.errors.0 }}</p>
              {% endif %}
              <label class="label">Repite la contraseña</label>
              {{ form.password2 }}
              {% if form.password2.errors %}
                <p class="text-red-500 text-xs">{{ form.password2.errors.0 }}</p>
              {% endif %}
              <div>
                <input required type="checkbox" class="checkbox checkbox-xs" />&nbsp; Al registrarte, aceptas nuestros <a href="{% url 'info:terms_and_conditions' %}" target="_blank" class="link link-primary link-hover">Términos y Condiciones</a> y nuestra <a href="{% url 'info:privacy_policy' %}" target="_blank" class="link link-primary link-hover">Política de Privacidad</a>.
              </div>
              <button type="submit" class="btn btn-primary">Registrarse</button>
              <a href="{% url 'info:index' %}" class="btn btn-neutral">Cancelar</a>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}