apps/dashboard/urls.py
from django.urls import path

from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
]

apps/geo/urls.py
from django.urls import path

from . import views

app_name = "info"

urlpatterns = [
    path("cities/", views.cities, name="cities"),
    path("courts/", views.courts, name="courts"),
]

apps/rankings/urls.py
from django.urls import path

from . import views

app_name = "rankings"

urlpatterns = [
    path("ranking_elo_players/", views.ranking_elo_players, name="ranking_elo_players"),
    path("ranking_elo_teams/", views.ranking_elo_teams, name="ranking_elo_teams"),
]

apps/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("public-profile/<int:user_id>/", views.PublicProfileView.as_view(), name="public_profile"),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("", include("apps.info.urls")),
    path("users/", include("apps.users.urls", namespace="users")),
    path("dashboard/", include("apps.dashboard.urls", namespace="dashboard")),
    path("rankings/", include("apps.rankings.urls", namespace="rankings")),
    path("geo/", include("apps.geo.urls", namespace="geo")),
    path("tienda/", include("apps.store.urls", namespace="store")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/components/button.html
<a href="{{ url|default:'#' }}" class="{{ extra_classes|default:'' }}">{{ label }}</a>

src/templates/components/card.html
<div class="card bg-base-200 w-96 shadow-sm">
  <div class="card-body items-center text-center">
    <h2 class="card-title">{{ title }}</h2>
    <p>{{ description }}</p>
  </div>
</div>

src/templates/components/geo-card.html
<div class="card bg-base-200 w-96 shadow-sm cursor-pointer" onclick="map_modal.showModal()">
  <figure>
    <img src="https://img.daisyui.com/images/stock/photo-1606107557195-0e29a4b5b4aa.webp" alt="Shoes" />
  </figure>
  <div class="card-body">
    <h2 class="card-title">{{ name }}<div class="badge badge-secondary">NEW</div></h2>
    <p>{{ description }}</p>
    <div class="card-actions justify-end">
      <div class="badge badge-outline">{{ geo }}</div>
    </div>
  </div>
</div>

{% if latitude %}
  <dialog id="map_modal" class="modal">
    <div class="modal-box w-11/12 max-w-5xl">
      <h3 class="text-lg font-bold">{{ name }}</h3>
      {% include 'components/map.html' with latitude=court.latitude longitude=court.longitude google_maps_api_key=google_maps_api_key %}
      <div class="modal-action">
        <form method="dialog">
          <button class="btn btn-accent">Cerrar</button>
        </form>
      </div>
    </div>
  </dialog>
{% endif %}

src/templates/components/map.html
<iframe
width="100%" 
height="500" 
style="border:0" 
loading="lazy" 
allowfullscreen 
referrerpolicy="no-referrer-when-downgrade" 
src="https://www.google.com/maps/embed/v1/place?key={{ google_maps_api_key }}
    &q={{ latitude }},{{ longitude }}
    &center={{ latitude }},{{ longitude }}
    &zoom=18
    &maptype=satellite">
</iframe>

src/templates/components/navbar.html
{% load static %}
<div class="navbar bg-base-200 shadow-sm">
  <div class="navbar-start">
    <div class="dropdown">
      <div tabindex="0" role="button" class="btn btn-ghost lg:hidden">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" />
        </svg>
      </div>
      <ul tabindex="0" class="menu menu-sm dropdown-content bg-base-100 rounded-box z-1 mt-3 w-52 p-2 shadow">
        <li>
          <details>
            <summary>Ranking</summary>
            <ul class="p-2 z-[999]">
              <li>
                <a href="{% url 'rankings:ranking_elo_players' %}">Jugadores</a>
              </li>
              <li>
                <a href="{% url 'rankings:ranking_elo_teams' %}">Equipos</a>
              </li>
            </ul>
          </details>
        </li>
        <li>
          <a href="{% url 'geo:cities' %}">Ciudades</a>
        </li>
        <li>
          <a href="{% url 'geo:courts' %}">Canchas</a>
        </li>
        <li>
          <a>Parent</a>
          <ul class="p-2">
            <li>
              <a>Submenu 1</a>
            </li>
            <li>
              <a>Submenu 2</a>
            </li>
          </ul>
        </li>
        <li>
          <a>Item 3</a>
        </li>
      </ul>
    </div>
    <a href="{% url 'dashboard:dashboard' %}" class="btn btn-ghost text-xl">Cancha3x3</a>
  </div>
  <div class="navbar-center hidden lg:flex">
    <ul class="menu menu-horizontal px-1">
      <li>
        <details>
          <summary>Ranking</summary>
          <ul class="p-2 z-[999]">
            <li>
              <a href="{% url 'rankings:ranking_elo_players' %}">Jugadores</a>
            </li>
            <li>
              <a href="{% url 'rankings:ranking_elo_teams' %}">Equipos</a>
            </li>
          </ul>
        </details>
      </li>
      <li>
        <a href="{% url 'geo:cities' %}">Ciudades</a>
      </li>
      <li>
        <a href="{% url 'geo:courts' %}">Canchas</a>
      </li>
      <li>
        <details>
          <summary>Parent</summary>
          <ul class="p-2">
            <li>
              <a>Submenu 1</a>
            </li>
            <li>
              <a>Submenu 2</a>
            </li>
          </ul>
        </details>
      </li>
      <li>
        <a>Item 3</a>
      </li>
    </ul>
  </div>
  <div class="navbar-end">
    <button class="avatar cursor-pointer" popovertarget="popover-1" style="anchor-name: --anchor-1">
      <div class="mask mask-squircle w-12">
        {% if user.avatar %}
          <img src="{{ user.avatar.url }}" alt="Avatar del usuario" width="150" />
        {% else %}
          <img src="{% static 'images/default_avatar.webp' %}" alt="Avatar por defecto" width="150" />
        {% endif %}
      </div>
    </button>

    <ul class="dropdown dropdown-end menu w-52 rounded-box bg-base-100 shadow-sm z-[999]" popover id="popover-1" style="position-anchor: --anchor-1">
      <li>
        <a>Perfil</a>
      </li>
      <label class="toggle text-base-content mx-2 my-2">
        <input type="checkbox" value="night" class="theme-controller" />

        <svg aria-label="sun" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
          <g stroke-linejoin="round" stroke-linecap="round" stroke-width="2" fill="none" stroke="currentColor">
            <circle cx="12" cy="12" r="4"></circle>
            <path d="M12 2v2"></path>
            <path d="M12 20v2"></path>
            <path d="m4.93 4.93 1.41 1.41"></path>
            <path d="m17.66 17.66 1.41 1.41"></path>
            <path d="M2 12h2"></path>
            <path d="M20 12h2"></path>
            <path d="m6.34 17.66-1.41 1.41"></path>
            <path d="m19.07 4.93-1.41 1.41"></path>
          </g>
        </svg>

        <svg aria-label="moon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
          <g stroke-linejoin="round" stroke-linecap="round" stroke-width="2" fill="none" stroke="currentColor">
            <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z"></path>
          </g>
        </svg>
      </label>
      <div class="divider"></div>
      <li>
        <a href="#" hx-post="{% url 'users:logout' %}" hx-include="[name=csrfmiddlewaretoken]" hx-target="body" hx-swap="none">Cerrar sesión</a>
        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />
      </li>
    </ul>
  </div>
</div>

src/templates/components/team_card.html
{% load static %}
<ul class="list bg-base-100 rounded-box shadow-md">
  {% for team in teams %}
    <li class="list-row">
      <div class="avatar">
        <div class="mask mask-squircle w-18">
          {% if team.logo %}
            <img src="{{ team.logo.url }}" alt="Logo del equipo" width="150" />
          {% else %}
            <img src="{% static 'images/default_logo.webp' %}" alt="Logo por defecto" width="150" />
          {% endif %}
        </div>
      </div>
      <div>
        <div class="text-2xl">{{ team.name }}</div>
        <div class="text-xl uppercase font-semibold opacity-60">Remaining Reason</div>
      </div>
    </li>
  {% endfor %}
</ul>