apps/rankings/urls.py
from django.urls import path

from . import views

app_name = "rankings"

urlpatterns = [
    path("ranking_elo_players/", views.ranking_elo_players, name="ranking_elo_players"),
    path("ranking_elo_teams/", views.ranking_elo_teams, name="ranking_elo_teams"),
]

apps/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("public-profile/<int:user_id>/", views.PublicProfileView.as_view(), name="public_profile"),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("", include("apps.info.urls")),
    path("users/", include("apps.users.urls", namespace="users")),
    path("dashboard/", include("apps.dashboard.urls", namespace="dashboard")),
    path("rankings/", include("apps.rankings.urls", namespace="rankings")),
    path("geo/", include("apps.geo.urls", namespace="geo")),
    path("tienda/", include("apps.store.urls", namespace="store")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/rankings/models.py
from django.db import models

# Create your models here.
class PlayerRanking(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    player = models.ForeignKey('users.Player', on_delete=models.CASCADE)
    elo = models.IntegerField(default=1500)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return f"{self.date.strftime('%Y-%m-%d %H:%M:%S')} - {self.player.username} - {self.elo} ELO"

apps/rankings/forms.py
from django import forms
from .models import PlayerRanking

class PlayerRankingForm(forms.ModelForm):
    class Meta:
        model = PlayerRanking
        fields = ['player', 'elo']

apps/rankings/views.py
from datetime import date
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from apps.rankings.models import PlayerRanking
from apps.teams.models import Team, TeamMember
from django.db.models.functions import TruncDate
from django.db.models import Avg, Subquery, OuterRef, Q, Max
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.template.loader import render_to_string

ITEMS_PER_PAGE = 10

# Create your views here.
@login_required
def ranking_elo_players(request):
    page_number = request.GET.get("page", 1)
    player_ranking, start_index = _get_ordered_player_ranking(page_number)
    historical_player_ranking = _get_historical_players_ranking()
    user = request.user

    if request.htmx:
        html = render_to_string(
            "partials/partial_ranking_table.html",
            {
                "player_ranking": player_ranking,
                "historical_player_ranking": historical_player_ranking,
                "user": user,
                "start_index": start_index,
            },
        )
        return HttpResponse(html)

    return render(
        request,
        "elo_tables.html",
        {
            "player_ranking": player_ranking,
            "historical_player_ranking": historical_player_ranking,
            "user": user,
            "start_index": start_index,
        },
    )


@login_required
def ranking_elo_teams(request):
    page_number = request.GET.get("page", 1)
    team_ranking, start_index = _get_ordered_team_ranking(page_number)

    if request.htmx:
        html = render_to_string(
            "partials/partial_ranking_table.html",
            {
                "team_ranking": team_ranking,
                "start_index": start_index,
            },
        )
        return HttpResponse(html)

    return render(
        request,
        "elo_tables.html",
        {
            "team_ranking": team_ranking,
            "start_index": start_index,
        },
    )


def _get_ordered_player_ranking(page_number, per_page=ITEMS_PER_PAGE):
    latest_ids = (
        PlayerRanking.objects.values("player_id")
        .annotate(latest_id=Max("id"))
        .values_list("latest_id", flat=True)
    )
    player_ranking = (
        PlayerRanking.objects.filter(id__in=latest_ids)
        .select_related("player")
        .order_by("-elo", "player__username")
    )

    paginator = Paginator(player_ranking, per_page)
    players = paginator.get_page(page_number)

    return players, (int(page_number) - 1) * per_page


def _get_historical_players_ranking():
    best_rankings = PlayerRanking.objects.filter(player=OuterRef("player")).order_by(
        "-elo"
    )

    historical_players_ranking = (
        PlayerRanking.objects.select_related("player")
        .filter(pk=Subquery(best_rankings.values("pk")[:1]))
        .order_by("-elo", "player__username")
    )

    return historical_players_ranking


def _get_ordered_team_ranking(page_number, per_page=ITEMS_PER_PAGE):
    today = date.today()

    latest_ranking_subquery = (
        PlayerRanking.objects.filter(player=OuterRef("player"))
        .order_by("-date")
        .values("elo")[:1]
    )

    active_members = (
        TeamMember.objects.annotate(
            join_date_only=TruncDate("join_date"),
            leave_date_only=TruncDate("leave_date"),
        )
        .filter(
            Q(join_date_only__lte=today),
            Q(leave_date_only__isnull=True) | Q(leave_date_only__gte=today),
        )
        .annotate(latest_elo=Subquery(latest_ranking_subquery))
    )

    teams_with_avg_elo = (
        Team.objects.filter(members__in=active_members)
        .annotate(
            average_elo=Avg(
                Subquery(
                    PlayerRanking.objects.filter(player=OuterRef("members__player"))
                    .order_by("-date")
                    .values("elo")[:1]
                )
            )
        )
        .order_by("-average_elo", "name")
    )

    paginator = Paginator(teams_with_avg_elo, per_page)
    teams_with_avg_elo = paginator.get_page(page_number)

    return teams_with_avg_elo, (int(page_number) - 1) * per_page

apps/rankings/templates/elo_players_table.html
{% load static %}
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Avatar</th>
      <th>Username</th>
      <th>ELO</th>
      <th>Reputación</th>
    </tr>
  </thead>
  <tbody>
    {% for player in player_ranking %}
      {% if player.player.id == user.id %}
        <tr class="bg-secondary text-secondary-content hover:bg-accent hover:text-accent-content">
      {% else %}
        <tr class="hover:bg-accent hover:text-accent-content">
      {% endif %}
          <th>{{ forloop.counter|add:start_index }}</th>
          <td>
            <div class="avatar">
              <div class="mask mask-squircle h-12 w-12">
                {% if player.player.avatar %}
                  <img src="{{ player.player.avatar.url }}" alt="Avatar del jugador" width="150" />
                {% else %}
                  <img src="{% static 'images/default_avatar.webp' %}" alt="Avatar por defecto" width="150" />
                {% endif %}
              </div>
            </div>
          </td>
          <td><a href="{% url 'users:public_profile' player.player.id %}">{{ player.player.username }}</a></td>
          <td>
            {% if player.elo >= 2400 %}
              <span class="text-success">{{ player.elo|floatformat:'0' }}</span>
            {% else %}
              {{ player.elo|floatformat:'0' }}
            {% endif %}
          </td>
          <td>
            {% if player.player.reputation_score < 0 %}
              <span class="text-error">{{ player.player.reputation_score|floatformat:'0' }}</span>
            {% else %}
              {{ player.player.reputation_score|floatformat:'0' }}
            {% endif %}
          </td>
        </tr>
    {% endfor %}
  </tbody>
</table>

apps/rankings/templates/elo_tables.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
  {% include 'components/navbar.html' %}
{% endblock %}

{% block content %}
  <!-- name of each tab group should be unique -->
  <div class="tabs tabs-box flex justify-center my-8">
    <input type="radio" name="my_tabs_6" class="tab my-2" aria-label="Live" checked="checked" />
    <div class="tab-content bg-base-100 border-base-300 p-6">
      <div class="overflow-x-auto" id="ranking-container">
        {% if player_ranking %}
          <h2 class="text-2xl text-center pb-2">Clasificación de Jugadores</h2>
          {% include 'elo_players_table.html' with player_ranking=player_ranking user=user %}
        {% elif team_ranking %}
          <h2 class="text-2xl text-center pb-2">Clasificación de Equipos</h2>
          {% include 'elo_teams_table.html' with team_ranking=team_ranking %}
        {% else %}
          <p class="text-center">No hay datos disponibles.</p>
        {% endif %}
        {% include 'partials/pagination_buttons.html' with page_obj=player_ranking %}
        {% include 'partials/pagination_buttons.html' with page_obj=team_ranking %}
      </div>
    </div>

    <input type="radio" name="my_tabs_6" class="tab my-2" aria-label="Histórico" />
    <div class="tab-content bg-base-100 border-base-300 p-6">
      <div class="overflow-x-auto">
        {% if historical_player_ranking %}
          <h2 class="text-2xl text-center pb-2">Clasificación Histórica de Jugadores</h2>
          {% include 'elo_players_table.html' with player_ranking=historical_player_ranking user=user %}
        {% elif historical_teams_ranking %}
          <h2 class="text-2xl text-center pb-2">Clasificación Histórica de Equipos</h2>
          {% include 'elo_teams_table.html' with team_ranking=historical_teams_ranking %}
        {% else %}
          <p class="text-center">No hay datos históricos disponibles.</p>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

apps/rankings/templates/elo_teams_table.html
{% load static %}
<table class="table table-zebra">
  <!-- head -->
  <thead>
    <tr>
      <th></th>
      <th>Escudo</th>
      <th>Equipo</th>
      <th>ELO</th>
    </tr>
  </thead>
  <tbody>
    {% for team in team_ranking %}
      <tr class="hover:bg-accent hover:text-accent-content">
        <th>{{ forloop.counter|add:start_index }}</th>
        <td>
          <div class="avatar">
            <div class="mask mask-squircle h-12 w-12">
              {% if team.logo %}
                <img src="{{ team.logo.url }}" alt="Logo del equipo" width="150" />
              {% else %}
                <img src="{% static 'images/default_logo.webp' %}" alt="Logo por defecto" width="150" />
              {% endif %}
            </div>
          </div>
        </td>
        <td>{{ team.name }}</td>
        <td>
          {% if team.average_elo >= 2400 %}
            <span class="text-success">{{ team.average_elo|floatformat:'0' }}</span>
          {% elif team.average_elo >= 0 and team.average_elo < 2400 %}
            {{ team.average_elo|floatformat:'0' }}
          {% else %}
            0
          {% endif %}
        </td>
        <td></td>
      </tr>
    {% endfor %}
  </tbody>
</table>